references:
  container_java: &container_java
    working_directory: ~/circleci2-sample
    docker:
      - image: openjdk:8

  workspace_root: &workspace_root
      /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  load_code: &load_code
    run:
      name: load code from workspace
      command: |
          # Move all files and dotfiles to current directory
          mv /tmp/workspace/circleci2-sample/* /tmp/workspace/circleci2-sample/.[!.]* .

version: 2
jobs:
  checkout_code:
    <<: *container_java
    steps:
      - checkout
      - run:
          name: create workspace
          command: |
            mkdir -p /tmp/workspace/circleci2-sample
            mv * .[!.]* /tmp/workspace/circleci2-sample/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - circleci2-sample
  build:
    <<: *container_java
    steps:
      - *attach_workspace
      - *load_code
      - run:
          name: gradle build
          command: |
            ./gradlew build
workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
