references:
  container_java: &container_java
    working_directory: ~/circleci2-sample
    docker:
      - image: openjdk:8

  container_python: &container_python
    working_directory: ~/circleci2-sample
    docker:
      - image: python:3.6.1

  workspace_root: &workspace_root
      /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

version: 2
jobs:
  checkout_code:
    <<: *container_java
    steps:
      - checkout
      - run:
          name: create workspace
          command: |
            mkdir -p /tmp/workspace/circleci2-sample
            mv * .[!.]* /tmp/workspace/circleci2-sample/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - circleci2-sample
  build:
    <<: *container_java
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: gradle build
          command: |
            ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: save artifact
          command: |
            ./gradlew bootRepackage
      - run:
          name: create workspace
          command: |
            mkdir -p /tmp/workspace/circleci2-sample
            cp build/libs/circleci2-sample-0.0.1-SNAPSHOT.jar /tmp/workspace/circleci2-sample/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - circleci2-sample
  deploy:
    <<: *container_python
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: show artifact
          command: |
            ls -la /tmp/workspace/circleci2-sample/
      - restore_cache:
         keys:
           - pip-{{ checksum ".circleci/requirements.txt" }}
      - run:
         name: setup python
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r .circleci/requirements.txt
           aws --version
      - save_cache:
         key: pip-{{ checksum ".circleci/requirements.txt" }}
         paths:
          - "venv"
      - run:
          name: deploy
          command: |
            echo "Launch CodeDeploy..."

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
